"""
2_📊_Model_Diagnostics.py — Cluster quality, stability, and per-cluster
breakdown. Surfaces all metrics from outputs/metrics.json plus the static
diagnostic figures generated by Stage 5.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import OUTPUTS_DIR, PROCESSED_DIR, VIZ_DATA_FILE  # noqa: E402
from src.utils import read_json  # noqa: E402

VIZ_DATA_PATH = PROCESSED_DIR / VIZ_DATA_FILE
METRICS_PATH = OUTPUTS_DIR / "metrics.json"

st.set_page_config(
    page_title="Model Diagnostics · NYC Congestion",
    page_icon="📊",
    layout="wide",
)

st.markdown(
    """
    <style>
      .main > div { padding-top: 1rem; }
      .diag-hero {
        background: linear-gradient(135deg, #1a1f2e 0%, #2d3748 100%);
        padding: 1.6rem 2rem; border-radius: 12px; border-left: 4px solid #2ecc71;
        margin-bottom: 1.25rem;
      }
      .diag-hero h1 { color: #2ecc71; margin: 0; font-size: 2rem; letter-spacing: -0.02em; }
      .diag-hero p  { color: #a0aec0; margin: 0.25rem 0 0; }
      .metric-card {
        background: #1a1f2e; border: 1px solid #2d3748; border-radius: 10px;
        padding: 1rem 1.2rem; height: 100%; border-left: 3px solid #3498db;
      }
      .metric-label {
        font-size: 0.78rem; color: #94a3b8; text-transform: uppercase;
        letter-spacing: 0.06em; margin-bottom: 0.25rem;
      }
      .metric-value {
        font-size: 1.7rem; font-weight: 700; color: #f1f5f9;
        line-height: 1.1; font-variant-numeric: tabular-nums;
      }
      .metric-trend { font-size: 0.85rem; color: #64748b; margin-top: 0.3rem; }
      .pass { border-left-color: #2ecc71; }
      .warn { border-left-color: #f39c12; }
      .fail { border-left-color: #e74c3c; }
      .section-h {
        font-size: 1.15rem; font-weight: 600; color: #e2e8f0;
        margin: 1.4rem 0 0.6rem 0;
        border-bottom: 1px solid #2d3748;
        padding-bottom: 0.4rem;
      }
      .desc { color: #94a3b8; font-size: 0.92rem; margin: 0.3rem 0 1rem; }

      /* Rename the bare "app" entry in the sidebar nav to something proper. */
      [data-testid="stSidebarNav"] ul li:first-child a span:not([role]) ,
      [data-testid="stSidebarNav"] ul li:first-child a p {
        display: none !important;
      }
      [data-testid="stSidebarNav"] ul li:first-child a::after {
        content: "🏠  Dashboard";
        color: inherit;
        font-size: 0.95rem;
        font-weight: 500;
        margin-left: 0.15rem;
      }
    </style>
    """,
    unsafe_allow_html=True,
)

PLOT_BG = "#1a1f2e"; GRID = "#2d3748"; TEXT = "#cbd5e1"


@st.cache_data(show_spinner=False)
def _load_data() -> pd.DataFrame | None:
    if VIZ_DATA_PATH.exists():
        return pd.read_parquet(VIZ_DATA_PATH)
    return None


@st.cache_data(show_spinner=False)
def _load_metrics() -> dict | None:
    if METRICS_PATH.exists():
        try:
            return read_json(METRICS_PATH)
        except Exception:
            return None
    return None


df = _load_data()
metrics = _load_metrics()

# ── Hero ─────────────────────────────────────────────────────────────────────
st.markdown(
    """
    <div class='diag-hero'>
      <h1>📊 Model Diagnostics</h1>
      <p>How well does the clustering actually work? Quality metrics, seed-stability,
      per-cluster breakdown, and the diagnostic figures generated during training.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

if metrics is None:
    st.warning("No metrics file found at `outputs/metrics.json`. Run `make pipeline` first.")
    st.stop()

# ── Headline metrics ─────────────────────────────────────────────────────────
sil = float(metrics.get("silhouette_score", 0))
db = float(metrics.get("davies_bouldin", 0))
ch = float(metrics.get("calinski_harabasz", 0))
k = metrics.get("k", "—")
stab = metrics.get("stability", {}) or {}
ari_min = stab.get("ari_min", 0)
ari_mean = stab.get("ari_mean", 0)

st.markdown("<div class='section-h'>Headline metrics</div>", unsafe_allow_html=True)
st.markdown(
    "<div class='desc'>Three independent indicators of partition quality, plus the agreement "
    "between fits under different random seeds.</div>",
    unsafe_allow_html=True,
)

cols = st.columns(5)
sil_class = "pass" if sil >= 0.5 else ("warn" if sil >= 0.25 else "fail")
db_class = "pass" if db <= 1.0 else ("warn" if db <= 1.5 else "fail")
ari_class = "pass" if ari_min >= 0.80 else ("warn" if ari_min >= 0.6 else "fail")
with cols[0]:
    st.markdown(
        f"""<div class='metric-card {sil_class}'>
              <div class='metric-label'>Silhouette</div>
              <div class='metric-value'>{sil:+.3f}</div>
              <div class='metric-trend'>cohesion vs separation · target ≥ 0.5</div>
            </div>""", unsafe_allow_html=True)
with cols[1]:
    st.markdown(
        f"""<div class='metric-card {db_class}'>
              <div class='metric-label'>Davies–Bouldin</div>
              <div class='metric-value'>{db:.3f}</div>
              <div class='metric-trend'>lower is better · target ≤ 1.0</div>
            </div>""", unsafe_allow_html=True)
with cols[2]:
    st.markdown(
        f"""<div class='metric-card pass'>
              <div class='metric-label'>Calinski–Harabasz</div>
              <div class='metric-value'>{ch:,.0f}</div>
              <div class='metric-trend'>higher is better</div>
            </div>""", unsafe_allow_html=True)
with cols[3]:
    st.markdown(
        f"""<div class='metric-card {ari_class}'>
              <div class='metric-label'>ARI · seed stability</div>
              <div class='metric-value'>{ari_min:.3f}</div>
              <div class='metric-trend'>min across seed pairs · mean {ari_mean:.3f}</div>
            </div>""", unsafe_allow_html=True)
with cols[4]:
    st.markdown(
        f"""<div class='metric-card pass'>
              <div class='metric-label'>k (clusters)</div>
              <div class='metric-value'>{k}</div>
              <div class='metric-trend'>chosen by kneedle elbow</div>
            </div>""", unsafe_allow_html=True)

# ── Per-cluster silhouette ──────────────────────────────────────────────────
st.markdown("<div class='section-h'>Per-cluster silhouette</div>", unsafe_allow_html=True)
st.markdown(
    "<div class='desc'>The dataset-level silhouette is an average — but some clusters are tighter "
    "than others. A cluster with a low per-cluster silhouette is a candidate to investigate or merge.</div>",
    unsafe_allow_html=True,
)

per_cluster_sil = metrics.get("silhouette_per_cluster", {}) or {}
if per_cluster_sil:
    levels = sorted([int(k_) for k_ in per_cluster_sil.keys()])
    sil_vals = [per_cluster_sil[str(lv)] for lv in levels]
    palette = px.colors.sample_colorscale("RdYlGn", [v / max(sil_vals + [1e-9])
                                                     for v in sil_vals])

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=[f"Level {lv}" for lv in levels],
        y=sil_vals,
        marker_color=palette,
        marker_line_color="rgba(255,255,255,0.18)",
        marker_line_width=1,
        text=[f"{v:.3f}" for v in sil_vals],
        textposition="outside",
        textfont=dict(color=TEXT, size=11),
    ))
    fig.add_hline(y=sil, line_color="#f1c40f", line_dash="dash", line_width=2,
                  annotation_text=f"overall silhouette = {sil:.3f}",
                  annotation_position="top right",
                  annotation_font=dict(color="#f1c40f"))
    fig.update_layout(
        xaxis=dict(title="Cluster (congestion level)", color=TEXT),
        yaxis=dict(title="Silhouette coefficient", gridcolor=GRID, color=TEXT,
                   range=[min(0, min(sil_vals) - 0.05), max(sil_vals) + 0.08]),
        plot_bgcolor=PLOT_BG, paper_bgcolor=PLOT_BG, font=dict(color=TEXT),
        height=380, showlegend=False, margin=dict(l=50, r=20, t=30, b=40),
    )
    st.plotly_chart(fig, use_container_width=True)

# ── Cluster sizes & CVintra ────────────────────────────────────────────────
st.markdown("<div class='section-h'>Cluster sizes &amp; intra-cluster variability</div>",
            unsafe_allow_html=True)
st.markdown(
    "<div class='desc'>Cluster size shows how observation count is distributed; "
    "<b>CVintra</b> is the coefficient of variation of speed within each cluster — "
    "lower means the cluster is internally consistent on the metric we care about.</div>",
    unsafe_allow_html=True,
)

c1, c2 = st.columns(2, gap="medium")
with c1:
    sizes = metrics.get("cluster_sizes", {}) or {}
    if sizes:
        levels = sorted([int(k_) for k_ in sizes.keys()])
        size_vals = [sizes[str(lv)] for lv in levels]
        fig = go.Figure(go.Pie(
            labels=[f"Level {lv}" for lv in levels],
            values=size_vals,
            hole=0.55,
            marker=dict(colors=px.colors.qualitative.Set2,
                        line=dict(color=PLOT_BG, width=2)),
            textinfo="label+percent",
            textfont=dict(color="#fff", size=11),
        ))
        fig.update_layout(
            title=dict(text="Cluster size distribution", font=dict(size=14)),
            plot_bgcolor=PLOT_BG, paper_bgcolor=PLOT_BG, font=dict(color=TEXT),
            height=380, margin=dict(l=20, r=20, t=50, b=20),
            showlegend=False,
        )
        st.plotly_chart(fig, use_container_width=True)

with c2:
    cvintra = metrics.get("cvintra_by_level", {}) or {}
    if cvintra:
        levels = sorted([int(k_) for k_ in cvintra.keys()])
        cv_vals = [cvintra[str(lv)] for lv in levels]
        cv_pass = [v < 0.20 for v in cv_vals]
        colors = ["#2ecc71" if p else ("#f39c12" if v < 0.30 else "#e74c3c")
                  for p, v in zip(cv_pass, cv_vals)]
        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=[f"L{lv}" for lv in levels], y=cv_vals,
            marker_color=colors,
            marker_line_color="rgba(255,255,255,0.18)", marker_line_width=1,
            text=[f"{v*100:.1f}%" for v in cv_vals],
            textposition="outside", textfont=dict(color=TEXT, size=10),
        ))
        fig.add_hline(y=0.20, line_color="#f1c40f", line_dash="dash",
                      annotation_text="20% target",
                      annotation_position="top right",
                      annotation_font=dict(color="#f1c40f"))
        fig.update_layout(
            title=dict(text="CVintra (speed) by cluster", font=dict(size=14)),
            xaxis=dict(title="Cluster", color=TEXT),
            yaxis=dict(title="Coefficient of Variation",
                       gridcolor=GRID, color=TEXT, tickformat=".0%"),
            plot_bgcolor=PLOT_BG, paper_bgcolor=PLOT_BG, font=dict(color=TEXT),
            height=380, showlegend=False, margin=dict(l=50, r=20, t=50, b=40),
        )
        st.plotly_chart(fig, use_container_width=True)

# ── Cluster centroids in feature space ──────────────────────────────────────
centroids = metrics.get("centroid_means", {}) or {}
if centroids:
    st.markdown("<div class='section-h'>Cluster centroids in feature space</div>",
                unsafe_allow_html=True)
    st.markdown(
        "<div class='desc'>Each cluster's centroid, in the standardised feature space the model trained on. "
        "This is what each cluster <i>is</i>: read across the row to interpret the cluster.</div>",
        unsafe_allow_html=True,
    )
    rows = []
    for lvl_str, feat_dict in centroids.items():
        row = {"Cluster": f"L{int(lvl_str)}"}
        row.update({k: round(float(v), 3) for k, v in feat_dict.items()})
        rows.append(row)
    cdf = pd.DataFrame(rows).sort_values("Cluster").reset_index(drop=True)
    st.dataframe(cdf, use_container_width=True, hide_index=True)

    # Radar / spider plot of centroids
    feature_keys = [c for c in cdf.columns if c not in ("Cluster",
                                                        "avg_speed_mph", "trip_density")]
    fig = go.Figure()
    for _, row in cdf.iterrows():
        vals = [row[k] for k in feature_keys] + [row[feature_keys[0]]]
        labs = feature_keys + [feature_keys[0]]
        fig.add_trace(go.Scatterpolar(
            r=vals, theta=labs, name=row["Cluster"], fill="toself", opacity=0.45,
        ))
    fig.update_layout(
        title=dict(text="Cluster centroids — radar view", font=dict(size=14)),
        polar=dict(
            bgcolor=PLOT_BG,
            radialaxis=dict(visible=True, gridcolor=GRID, color=TEXT,
                            angle=90, tickfont=dict(size=9)),
            angularaxis=dict(gridcolor=GRID, color=TEXT,
                             tickfont=dict(size=10)),
        ),
        plot_bgcolor=PLOT_BG, paper_bgcolor=PLOT_BG, font=dict(color=TEXT),
        legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color=TEXT, size=11)),
        height=520, margin=dict(l=20, r=20, t=50, b=20),
    )
    st.plotly_chart(fig, use_container_width=True)

# ── Static diagnostic figures ───────────────────────────────────────────────
st.markdown("<div class='section-h'>Diagnostic figures</div>", unsafe_allow_html=True)
st.markdown(
    "<div class='desc'>Generated by Stage 5 of the pipeline. These are saved to "
    "<code>outputs/</code> for use in reports and supplementary materials.</div>",
    unsafe_allow_html=True,
)

figures = [
    ("elbow_curve.png", "Elbow / inertia curve",
     "x = k. y = within-cluster sum of squares. The knee marks where adding another cluster stops paying off."),
    ("model_selection.png", "Joint model selection",
     "Inertia and silhouette plotted against k on a shared x-axis."),
    ("cluster_distribution.png", "Cluster size distribution",
     "How many zone-hour observations land in each cluster."),
    ("cluster_profile.png", "Cluster profile — feature centroids",
     "Each cluster's mean across the feature set; lets you describe each cluster qualitatively."),
    ("speed_deviation_histogram.png", "speed_deviation histogram",
     "x = Δ in mph. y = count. Tells you how the deviation feature is distributed across the dataset."),
    ("speed_deviation_scatter.png", "Speed deviation vs density",
     "Scatter of zone-hours; congestion clusters separate naturally along this axis pair."),
    ("speed_density_by_hour.png", "Speed and density by hour-of-day",
     "Two y-axes — average speed (line) and trip density (bars) — across hour 0–23."),
    ("monthly_trend.png", "Monthly trend",
     "How average speed and density evolve month-over-month across the 6-month window."),
    ("congestion_heatmap.png", "Day × hour congestion heatmap",
     "x = hour. y = day-of-week. Colour = avg congestion level."),
    ("zone_hour_heatmap.png", "Top zones × hour",
     "x = hour. y = zone (top-N by activity). Colour = avg congestion level."),
    ("top_congested_zones.png", "Top congested zones",
     "Bar chart ranking zones by average congestion level."),
]

for i in range(0, len(figures), 2):
    pair = figures[i:i + 2]
    cols = st.columns(len(pair), gap="medium")
    for col, (fname, title, caption) in zip(cols, pair):
        path = OUTPUTS_DIR / fname
        with col:
            if path.exists():
                st.markdown(
                    f"<div style='color:#f1c40f;font-weight:700;margin-bottom:0.3rem'>{title}</div>",
                    unsafe_allow_html=True,
                )
                st.image(str(path), use_container_width=True)
                st.caption(caption)
            else:
                st.info(f"`{fname}` not found. Run `make pipeline` to generate.")

st.divider()
st.caption("All metrics regenerate when you re-run `make pipeline`.")
